app/__init__.py
from flask import Flask,request, g, abort
import os
import ast
import ConfigParser
from logging.handlers import RotatingFileHandler
from flask.ext.babel import Babel
from flask.ext.mail import Mail


mail=Mail()
#Initialize mongo access point

babel = Babel()

def create_app():
    # Here we  create flask instance

    app = Flask(__name__)
    app.secret_key = 'random string'
    # Load application configurations
    load_config(app)

    # Configure logging.
    configure_logging(app)

    # Init modules
    init_modules(app)
    mail.init_app(app)
    # Initialize the app to work with MongoDB



    babel.init_app(app)

    # Get local based on domain name used.
    @babel.localeselector
    def get_locale():
        """Direct babel to use the language defined in the session."""
        return g.get('current_lang', 'sr')


    @app.before_request
    def before():
        if request.view_args and 'lang_code' in request.view_args:
            if request.view_args['lang_code'] not in ('sr', 'en'):
                return abort(404)
            g.current_lang = request.view_args['lang_code']
            request.view_args.pop('lang_code')

    return app

def load_config(app):
    ''' Reads the config file and loads configuration properties into the Flask app.
    :param app: The Flask app object.
    '''
    # Get the path to the application directory, that's where the config file resides.
    par_dir = os.path.join(__file__, os.pardir)
    par_dir_abs_path = os.path.abspath(par_dir)
    app_dir = os.path.dirname(par_dir_abs_path)

    # Read config file
    config = ConfigParser.RawConfigParser()
    config_filepath = app_dir + '/config.cfg'
    config.read(config_filepath)

    app.config['MAIL_SERVER'] = config.get('Mail', 'MAIL_SERVER')
    app.config['MAIL_PORT'] = config.get('Mail', 'MAIL_PORT')
    app.config['MAIL_USE_SSL'] = ast.literal_eval(config.get('Mail', 'MAIL_USE_SSL'))
    app.config['MAIL_USE_TLS'] = ast.literal_eval(config.get('Mail', 'MAIL_USE_TLS'))
    app.config['MAIL_USERNAME'] = config.get('Mail', 'MAIL_USERNAME')
    app.config['MAIL_PASSWORD'] = config.get('Mail', 'MAIL_PASSWORD')

    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
    app.config['MONGO_DBNAME'] = config.get('Mongo', 'DB_NAME')

    # Logging path might be relative or starts from the root.
    # If it's relative then be sure to prepend the path with the application's root directory path.
    log_path = config.get('Logging', 'PATH')
    if log_path.startswith('/'):
        app.config['LOG_PATH'] = log_path
    else:
        app.config['LOG_PATH'] = app_dir + '/' + log_path

    app.config['LOG_LEVEL'] = config.get('Logging', 'LEVEL').upper()


def configure_logging(app):
    ''' Configure the app's logging.
     param app: The Flask app object
    '''

    log_path = app.config['LOG_PATH']
    log_level = app.config['LOG_LEVEL']

    # If path directory doesn't exist, create it.
    log_dir = os.path.dirname(log_path)
    if not os.path.exists(log_dir):
        os.makedirs(log_dir)

    # Create and register the log file handler.
    log_handler = RotatingFileHandler(log_path, maxBytes=250000, backupCount=5)
    log_handler.setLevel(log_level)
    app.logger.addHandler(log_handler)

    # First log informs where we are logging to.
    # Bit silly but serves  as a confirmation that logging works.
    app.logger.info('Logging to: %s', log_path)


def init_modules(app):
    # Import blueprint modules
    from app.mod_main.views import mod_main
    from app.mod_type.views import mod_type
    from app.mod_api.views import mod_api
    from app.mod_contact.views import mod_contact
    from app.mod_questions.views import mod_questions
    app.register_blueprint(mod_main)
    app.register_blueprint(mod_type)
    app.register_blueprint(mod_api)
    app.register_blueprint(mod_contact)
    app.register_blueprint(mod_questions)




app/mod_api/views.py
# coding=utf-8
import pprint

from flask import Blueprint,request
from flask import render_template

import json,urllib


mod_api = Blueprint('api', __name__, url_prefix="/<lang_code>/api", static_folder="static", template_folder='templates')
#get data for all territories selected by year

@mod_api.route('/', methods=['GET'])
def api_page():
    return render_template('api/api.html',year=0)

app/mod_contact/views.py
# coding=utf-8
import pprint

from flask import Blueprint,request, redirect,url_for, flash
from flask import render_template
import json,urllib

from flask_mail import Message
from app import mail

mod_contact = Blueprint('contact', __name__, url_prefix="/<lang_code>/contact",static_folder="static", template_folder='templates', )
#get data for all territories selected by year

@mod_contact.route('/', methods=['GET'])
def contact_page():
    return render_template('contact/contact.html',year=0)

@mod_contact.route('/sendemail', methods=['POST'])
def send_email():
    data=request.form.to_dict()
    print data
    message ="from:" + data['email'] + '<br/>' + data['Message'] + '/n '
    msg = Message(subject=data['subject'],
                  sender=data['Name'],
                  recipients=["kontakt@gradjaninastrazi.rs"],
                  body=message)
    msg.html="<b>From:</b> " + data['email'] + '<br/><br/>' + data['Message']
    mail.send(msg)
    flash('Порука је успешно послата')
    return redirect(url_for('contact.contact_page'))

app/mod_main/views.py
from flask import Blueprint
from flask import render_template,redirect
import json,urllib
import heapq
mod_main = Blueprint('main', __name__)


@mod_main.route('/', methods=['GET'])
def index():
    return redirect("/sr", code=302)

@mod_main.route('/<lang_code>', methods=['GET'])
def root():
    return render_template('site/home.html',year=0)

app/mod_questions/views.py
# coding=utf-8
import pprint

from flask import Blueprint,request
from flask import render_template
import json,urllib


mod_questions = Blueprint('questions', __name__, url_prefix="/<lang_code>/questions",static_folder="static", template_folder='templates', )
#get data for all territories selected by year
@mod_questions.route('/', methods=['GET'])
def questions_page():
    return render_template('questions/questions.html',year=0)

app/mod_type/views.py
# coding=utf-8
import pprint

from flask import Blueprint,request
from flask import render_template

import json,urllib


mod_type = Blueprint('type', __name__, url_prefix="/<lang_code>/type",static_folder="static", template_folder='templates')
#get data for all territories selected by year
@mod_type.route('/<int:datasource>/<string:typeizbori>/<int:year>/<int:instanca>/krug/<string:krug>/status/<string:status>', methods=['GET'])
def electionType(datasource, typeizbori,year, instanca, krug, status):
    return render_template('type/type.html',typeizbori=typeizbori,year=year,instanca=instanca, krug=krug, status=status)

app/templates/contact/contact.html
{% extends "layout.html" %}
{% block body %}
<section style="padding-top:100px;">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12 body_pages">
                        <div class="row">
                            <h4 class="landingpage-h4">{{ _('Контакт') }}</h4>
                            <div class="arrow_left_side">
                                <img alt="elections" src="{{ url_for('static', filename = 'assets/arrow_elections-home.jpg') }}">
                            </div>
                        </div>
                        	<div class="row">
                                <form role="form" id="contact-form" class="contact-form" action="{{ url_for('contact.send_email',lang_code=g.current_lang) }}" method="POST">
{% with messages = get_flashed_messages() %}
  {% if messages %}

    {% for message in messages %}
        <div class="alert alert-success">
        <strong>{{ _('Успех') }}! </strong> {{ message.decode('utf-8') }}.
        </div>

    {% endfor %}

  {% endif %}
{% endwith %}
                                    <div class="row">
                                            <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="{{ _('Име') }}" required>
                                            </div>
                                        </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <input type="email" class="form-control" name="email" autocomplete="off" id="email" placeholder="{{ _('Е-маил') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="subject" autocomplete="off" id="email" placeholder="{{ _('Teмa') }}" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                            <div class="form-group">
                                                <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="{{ _('Порука') }}" required></textarea>
                                            </div>
                                        </div>
                                        </div>
                                        <div class="row">
                                        <div class="col-md-12">
                                      <button type="submit" class="btn main-btn pull-right" id="btn-email">{{ _('Пошаљи поруку') }}</button>
                                      </div>
                                      </div>
                                </form>
	                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
{% endblock %}
<script>
    $('#btn-email').click(function(){
            $('#contact-form').bootstrapValidator({
     live: 'disabled',
        message: 'This value is not valid',
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            Name: {
                validators: {
                    notEmpty: {
                        message: 'The Name is required and cannot be empty'
                    }
                }
            },
            email: {
                validators: {
                    notEmpty: {
                        message: 'The email address is required'
                    },
                    emailAddress: {
                        message: 'The email address is not valid'
                    }
                }
            },
            Message: {
                validators: {
                    notEmpty: {
                        message: 'The Message is required and cannot be empty'
                    }
                }
            }
        }
    });
    })

</script>

app/templates/include/election_tabs1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/include/election_tabs2.html
<div class="no-padding tabs-div">

            <div class="col-md-8 col-sm-12 col-xs-12 election-tabs-link">
                <p class="tab-link">Избори / бирачких спискова <span class="arrow_shape">▼</span></p>
                <div class="arrow"></div>
                {%  if typeizbori %}
                    {% if typeizbori=="parlamentarni" %}
                            <p class="selected-type">Парламентарни > {{ year }}</p>
                        {% endif %}
                    {% if typeizbori=="predsjednicki" %}
                            <p class="selected-type">Председнички > {{ year }}</p>
                        {% endif %}
                {%  endif %}
            </div>
        <div class="col-md-4 col-sm-12 col-xs-12 social-icons">
            <ul>
                <li>
                    <a href="https://www.facebook.com/sharer/sharer.php?u=&t=" class="fa fa-facebook-official" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' +encodeURIComponent(document.URL) + '&t='+ encodeURIComponent(document.title)); return false;">
                    </a>
                </li>
                <li>
                    <a href="https://twitter.com/intent/tweet?source=&amp;text=:%20" class="fa fa-twitter-square" target="_blank" onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title)+ ':%20'  + encodeURIComponent(document.URL)); return false;">
                    </a>
                </li>
            </ul>
        </div>
<style>
    .social-icons ul{
        list-style: none;
        width:200px;
        float:right;
    }
    .social-icons ul li{
        width: 60px;
        float: left;
    }
    .social-icons ul li a{
        font-size:30px;
        color:#337ab7;
    }
    .social-icons ul li a:hover{
        text-decoration:none;
    }
</style>
</div>

      <div class="tabs tabs-type-elections" id="tabs">
        <ul>
            <li id="presjednicki"><a href="#tabs-1">Председнички</a></li>
            <li id="parlamentarni"><a href="#tabs-2">Парламентарни</a></li>
        </ul>
          <div id="tabs-1" class="year-list-tabs">
            <ul>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='prvi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2002   - Први круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='drugi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2002  - Други круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2003, instanca='1', krug='drugi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2003  - Други круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2008, instanca='1', krug='prvi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2008   - Први круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2008, instanca='1', krug='drugi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2008   - Други круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2012, instanca='1', krug='prvi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2012  - Први круг</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2012, instanca='1', krug='drugi') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2012  - Други круг</a></li>

            </ul>
          </div>
          <div id="tabs-2"  class="year-list-tabs">
            <ul>
                        <li> <a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2003, instanca='1', krug='none') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2003</a></li>
                         <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2008, instanca='1', krug='none') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2008</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2012, instanca='1', krug='none') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2012</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2014, instanca='4', krug='none') }}"><img alt="Menu_official" src="{{ url_for('static', filename = 'assets/menu_link_year.png') }}">2014</a></li>


        {#                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2007, instanca='4', krug='none') }}">2007</a></li>
                        <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2016, instanca='4', krug='none') }}">2016</a></li>#}
                        <!-- second data source -->

            </ul>
          </div>
      </div>
<style>
    .fb-share-button span{
        height:44px !important;
    }
</style>

app/templates/include/footer.html
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-3 col-sm-12">
                            <div class="extend">
                                <div class="grandjani-logo" style="text-align: center;margin-top:20px;">
                                 <a  href="http://www.gradjaninastrazi.rs/" target="_blank"><img alt="" src="{{ url_for('static', filename = 'assets/logo_cropped.png') }}"></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3  col-sm-12 footer-list">
                            <h2>{{ _('Председнички') }}</h2>
                            <div class="col-lg-6 col-md-12 col-sm-12 pres-list">
                                 <ul>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='prvi',status='none',lang_code=g.current_lang) }}">2002-{{ _('Први круг') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='drugi',status='none',lang_code=g.current_lang) }}">2002-{{ _('Други круг') }}</a></li>
                                   <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='prvi',status='ponovljeni',lang_code=g.current_lang) }}">2002-{{ _('Поновљени') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2003, instanca='1', krug='prvi',status='none',lang_code=g.current_lang) }}">2003-{{ _('Први круг') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2008, instanca='1', krug='prvi',status='none',lang_code=g.current_lang) }}">2008-{{ _('Први круг') }}</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-6 col-md-12 col-sm-12 pres-list">
                                <ul>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2008, instanca='1', krug='drugi',status='none',lang_code=g.current_lang) }}">2008-{{ _('Други круг') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2012, instanca='1', krug='prvi',status='none',lang_code=g.current_lang) }}">2012-{{ _('Први круг') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2012, instanca='1', krug='drugi',status='none',lang_code=g.current_lang) }}">2012-{{ _('Други круг') }}</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2017, instanca='1', krug='prvi',status='none',lang_code=g.current_lang) }}">2017-{{ _('Први круг') }}</a></li>
                                </ul>
                            </div>

                        </div>
                         <div class="col-md-3 col-sm-12 footer-list">
                                <h2>{{ _('Парламентарни') }}</h2>
                             <div class="col-md-3">
                                 <ul>
                                    <li> <a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2003, instanca='1', krug='none',status='none',lang_code=g.current_lang) }}">2003</a></li>
                                     <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2007, instanca='1', krug='none',status='none',lang_code=g.current_lang) }}">2007</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2008, instanca='1', krug='none',status='none',lang_code=g.current_lang) }}">2008</a></li>

                                </ul>
                             </div>
                             <div class="col-md-3">
                                  <ul>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2012, instanca='1', krug='none',status='none',lang_code=g.current_lang) }}">2012</a></li>
                                    <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2014, instanca='4', krug='none',status='none',lang_code=g.current_lang) }}">2014</a></li>
                                       <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2016, instanca='4', krug='none',status='none',lang_code=g.current_lang) }}">2016</a></li>
                                </ul>
                             </div>

                         </div>

                        <div class="col-md-3 col-sm-12 footer-contact footer-list">
                            <h2>{{ _('Контакт') }}</h2>
                            <div class="row">
                                <div class="col-md-12"><p>{{ _('Емаил') }}: kontakt@gradjaninastrazi.rs </p></div>
                                <div class="col-md-12"><p>{{ _('Тел') }}: 011 2400062</p></div>
                            </div>

                        </div>
                    </div>
                </div>
                 <div class="col-md-12">
                    <div class="row footer-social">
                       <div class="col-md-4 col-sm-12 col-xs-12 social-icons">
                            <ul>
                                <li>
                                    <a href="https://www.facebook.com/sharer/sharer.php?u=&t=" class="fa fa-facebook-official" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' +encodeURIComponent(document.URL) + '&t='+ encodeURIComponent(document.title)); return false;">
                                    </a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/intent/tweet?source=&amp;text=:%20" class="fa fa-twitter-square" target="_blank" onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title)+ ':%20'  + encodeURIComponent(document.URL)); return false;">
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                 </div>

   <script> (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){ (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-76516915-1', 'auto'); ga('send', 'pageview'); </script>

app/templates/include/navigation1.html
<div class="no-padding tabs-div">
            <div class="col-md-9 col-sm-12 col-xs-12 election-tabs-link">
                <p>Избори / бирачких спискова <span class="arrow_shape">▼</span></p>
                <div class="arrow"></div>
                {%  if typeizbori %}
                    {% if typeizbori=="parlamentarni" %}
                            <p class="selected-type">Парламентарни > {{ year }}</p>
                        {% endif %}
                    {% if typeizbori=="predsjednicki" %}
                            <p class="selected-type">Председнички > {{ year }}</p>
                        {% endif %}
                {%  endif %}
            </div>
        <div class="col-md-3 col-sm-12 col-xs-12" id="social-media-icons">
            <div id="fb-root"></div>
            <script>
                    (function(d, s, id) {
                  var js, fjs = d.getElementsByTagName(s)[0];
                  if (d.getElementById(id)) return;
                  js = d.createElement(s); js.id = id;
                  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8&appId=1778236145760204";
                  fjs.parentNode.insertBefore(js, fjs);
                }(document, 'script', 'facebook-jssdk'));
            </script>
                <div class="fb-share-button" data-href="http://0.0.0.0:5024/" data-layout="button" data-size="large" data-mobile-iframe="true">
                    <a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse">
                        Share
                    </a>
                </div>
               <script>window.twttr = (function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0],
                        t = window.twttr || {};
                      if (d.getElementById(id)) return t;
                      js = d.createElement(s);
                      js.id = id;
                      js.src = "https://platform.twitter.com/widgets.js";
                      fjs.parentNode.insertBefore(js, fjs);

                      t._e = [];
                      t.ready = function(f) {
                        t._e.push(f);
                      };
                      return t;
                    }(document, "script", "twitter-wjs"));
               </script>

            <iframe
              src="https://platform.twitter.com/widgets/tweet_button.html?size=l&url=https%3A%2F%2Fdev.twitter.com%2Fweb%2Ftweet-button&via=twitterdev&related=twitterapi%2Ctwitter&text=custom%20share%20text&hashtags=example%2Cdemo"
              width="140"
              height="40"
              title="Twitter Tweet Button"
              style="border:none">
            </iframe>

        </div>


</div>

      <div class="tabs tabs-type-elections" id="tabs">
        <ul>
            <li id="presjednicki"><a href="#tabs-1">Председнички</a></li>
            <li id="parlamentarni"><a href="#tabs-2">Парламентарни</a></li>
        </ul>
          <div id="tabs-1" class="year-list-tabs">
            <ul>
                {#<li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='prvi') }}">2002   - Први круг</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2002, instanca='1', krug='drugi') }}">2002  - Други круг</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2003, instanca='1', krug='drugi') }}">2003  - Други круг</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2008, instanca='1', krug='prvi') }}">2008   - Први круг</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'predsjednicki', year=2012, instanca='1', krug='drugi') }}">2012  - Први круг</a></li>
#}


            </ul>
          </div>
          <div id="tabs-2"  class="year-list-tabs">
            <ul>
                <li>
                    <a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2003, instanca='1', krug='none') }}"><img alt="Menu_official" src="/static/assets/menu_link_year.png">2003</a>

                </li>
                 <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2008, instanca='1', krug='none') }}"><img alt="Menu_official" src="/static/assets/menu_link_year.png">2008</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2012, instanca='1', krug='none') }}"><img alt="Menu_official" src="/static/assets/menu_link_year.png">2012</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2014, instanca='4', krug='none') }}"><img alt="Menu_official" src="/static/assets/menu_link_year.png">2014</a></li>


{#                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2007, instanca='4', krug='none') }}">2007</a></li>
                <li><a href="{{ url_for('type.electionType', datasource='2', typeizbori = 'parlamentarni', year=2016, instanca='4', krug='none') }}">2016</a></li>#}
                <!-- second data source -->

                </li>
            </ul>
          </div>
      </div>
<style>
    .fb-share-button span{
        height:44px !important;
    }
</style>

app/templates/layout1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'include/head.html' %}
</head>
<body id="page-top">
<div class="container-fluid">
    {% include 'include/navigation.html' %}

    {% block body %}

    {% endblock %}
    <div class="push"></div>
</div>

<div id="contact">
    {% include 'include/footer.html' %}
</div>
</body>
<div class="loader"></div>
<style>
    .loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 99999;
        background: url("{{ url_for('static', filename = 'assets/page-loader.gif') }}") 50% 50% no-repeat rgb(249, 249, 249);
    }
</style>
</html>

app/templates/site/_map_parl_2012.html
   <div id="containermap_2012" class="col-md-12 col-sm-12 col-xs-12 lists div-map" style="height:200px;">
       <img src="{{ url_for("static",filename="assets/2012_map.png") }}"/>
    </div>

app/templates/site/_map_parl_2014.html
   <div id="containermap_2014" class="col-md-12 col-sm-12 col-xs-12 lists div-map" style="height:200px;">
           <img src="{{ url_for("static",filename="assets/2014_map.png") }}"/>
    </div>